- .gitignore
- decisioncentral/README.adoc
- decisioncentral/image.yaml
Depends on https://github.com/jboss-container-images/rhdm-7-image/pull/1
This is an initial version of the image, mostly copied from the BPMSuite one. I think we should create an initial working version with some duplication and then we can focus on moving thing into common modules to avoid duplication.
@spolti, @sutaakar, @AntStephenson could you please review?
> Add Decision Central image

- decisioncentral/image.yaml
Add osbs section for building in openshift. 
Signed-off-by: Ant Stephenson <anstephe@redhat.com>
> Add osbs section.

- decisioncentral/image.yaml
> standardize envs

- kieserver/image.yaml
Signed-off-by: Ant Stephenson <anstephe@redhat.com>
> Add osbs section to kieserver image.

- decisioncentral/image.yaml
- kieserver/image.yaml
Reverts jboss-container-images/rhdm-7-openshift-image#8
> Revert "[CLOUD-2235] KIE specific concreate modules moved to own repo"

- decisioncentral/image.yaml
- kieserver/image.yaml
The hawkular agent artifact is now included in the cct os-hawkular-java module
Signed-off-by: Paul Gier <pgier@redhat.com>
> [CLOUD-2081] remove hawular agent artifact

- decisioncentral/image.yaml
- kieserver/image.yaml
> use the correct eap modules

- .gitignore
- quickstarts/hello-rules/README.md
- quickstarts/hello-rules/hellorules-client/pom.xml
- quickstarts/hello-rules/hellorules-client/src/main/java/org/openshift/quickstarts/rhdm/kieserver/hellorules/client/HelloRulesCallback.java
- quickstarts/hello-rules/hellorules-client/src/main/java/org/openshift/quickstarts/rhdm/kieserver/hellorules/client/HelloRulesClient.java
- quickstarts/hello-rules/hellorules-client/src/main/java/org/openshift/quickstarts/rhdm/kieserver/hellorules/client/HelloRulesServlet.java
- quickstarts/hello-rules/hellorules-client/src/main/webapp/WEB-INF/jboss-deployment-structure.xml
- quickstarts/hello-rules/hellorules-client/src/main/webapp/WEB-INF/jboss-web.xml
- quickstarts/hello-rules/hellorules-client/src/main/webapp/WEB-INF/web.xml
- quickstarts/hello-rules/hellorules-client/src/test/java/org/openshift/quickstarts/rhdm/kieserver/hellorules/client/HelloRulesTest.java
- quickstarts/hello-rules/hellorules/pom.xml
- quickstarts/hello-rules/hellorules/src/main/java/org/openshift/quickstarts/rhdm/kieserver/hellorules/Greeting.java
- quickstarts/hello-rules/hellorules/src/main/java/org/openshift/quickstarts/rhdm/kieserver/hellorules/Person.java
- quickstarts/hello-rules/hellorules/src/main/resources/META-INF/kmodule.xml
- quickstarts/hello-rules/hellorules/src/main/resources/META-INF/org/openshift/quickstarts/rhdm/kie-server/hellorules/HelloRules.drl
- quickstarts/hello-rules/pom.xml
- templates/rhdm70-kieserver-s2i.yaml
Adding the hellorules quickstart using the bxms 7 version.
> Rhdm quickstart

- templates/rhdm70-kieserver-s2i.yaml
- templates/rhdm70-kieserver.yaml
> [RHDM-265] - Disabled Kie server sync deploy in templates

- decisioncentral/image.yaml
- kieserver/image.yaml
Signed-off-by: Kyle Liberti <kliberti@redhat.com>
> [CLOUD-2139] Upgrade Maven to 3.5

- quickstarts/hello-rules/hellorules-client/pom.xml
- quickstarts/hello-rules/hellorules/pom.xml
- quickstarts/hello-rules/pom.xml
- rhdm70-image-streams.yaml
- templates/rhdm70-full.yaml
- templates/rhdm70-kieserver-basic-s2i.yaml
- templates/rhdm70-kieserver-https-s2i.yaml
- templates/rhdm70-kieserver.yaml
[RHDM-354] - Add RHDM 7.0 GA templates and image streams to Openshift service catalog
> prepare xpaas release ose-v1.4.8-1

- decisioncentral/image.yaml
- kieserver/image.yaml
https://issues.jboss.org/browse/CLOUD-2351
> [CLOUD-2351] Container namespace switch

- CONTRIBUTING.md
> Add contributing instructions to rhdm-7-openshift-image repo

- decisioncentral/image.yaml
- kieserver/image.yaml
[RHDM-491] Rename RHDM OSBS repository branches
https://issues.jboss.org/browse/RHDM-491
> [RHDM-491] Rename RHDM OSBS repository branches

- decisioncentral/image.yaml
- kieserver/image.yaml
> [RHDM-492] - Update activemq-rar version on RHDM image

- templates/rhdm70-full.yaml
- templates/rhdm70-kieserver-basic-s2i.yaml
- templates/rhdm70-kieserver-https-s2i.yaml
- templates/rhdm70-kieserver.yaml
> [RHDM-494] - Increase Resource Memory limit in OpenShift templates

- templates/rhdm70-full.yaml
- templates/rhdm70-kieserver-basic-s2i.yaml
- templates/rhdm70-kieserver-https-s2i.yaml
- templates/rhdm70-kieserver.yaml
I have edited the description in parameters for all three templates, trying to bring them into full compliance with documentation guidelines in all three templates.
I would appreciate a review as I might have stated something wrong. Then I'll take one final look and then merge this. If the no-https template comes in I can replicate my changes there.
> [RHDM-503] edit descriptions of parameters in templates

- kieserver/image.yaml
> [CLOUD-2351] - Container namespace switch

- decisioncentral/image.yaml
- kieserver/image.yaml
Fixes https://issues.jboss.org/browse/RHDM-521
> [RHDM-521] Removed rh-maven33 dependency

- templates/rhdm70-full.yaml
- templates/rhdm70-kieserver-basic-s2i.yaml
- templates/rhdm70-kieserver-https-s2i.yaml
- templates/rhdm70-kieserver.yaml
Addresses RHDM templates for https://issues.jboss.org/browse/RHDM-319
> [RHDM-319] OpenShift - default Maven user should not be admin

- templates/rhdm70-kieserver.yaml
> Remove duplicated description on KIE server controller host env

- kieserver/image.yaml
- templates/rhdm70-kieserver-basic-s2i.yaml
- templates/rhdm70-kieserver-https-s2i.yaml
> [RHDM-587] - Allow KIE server / OpenShift to be completely immutable

- templates/rhdm70-full.yaml
> [RHDM-457] - Session error after being idle for a few minutes

- decisioncentral/image.yaml
- kieserver/image.yaml
Fixes https://issues.jboss.org/browse/RHDM-604
> [RHDM-604] Aligned logmanager version

- decisioncentral/image.yaml
Fixes https://issues.jboss.org/browse/RHDM-666
> [RHDM-666] Add git client to decision central

- templates/rhdm70-full.yaml
- templates/rhdm70-kieserver-basic-s2i.yaml
- templates/rhdm70-kieserver-https-s2i.yaml
- templates/rhdm70-kieserver.yaml
> [RHDM-319] - OpenShift - default Maven user should not be admin

- templates/rhdm70-full.yaml
> [RHDM-536] Allow access to the decision-central image git repository

- templates/docs/rhdm/rhdm70-full.adoc
- templates/docs/rhdm/rhdm70-kieserver-basic-s2i.adoc
- templates/docs/rhdm/rhdm70-kieserver-https-s2i.adoc
- templates/docs/rhdm/rhdm70-kieserver.adoc
> update templates docs

- decisioncentral/image.yaml
- kieserver/image.yaml
> update jboss-kie-modules to master

- templates/rhdm70-full.yaml
- templates/rhdm70-kieserver-basic-s2i.yaml
- templates/rhdm70-kieserver-https-s2i.yaml
- templates/rhdm70-kieserver.yaml
> version and rhdm label version should be between double quotes

- templates/rhdm71-full.yaml
Signed-off-by: Jakub Schwan jschwan@redhat.com
>  [RHDM-706] Liveness and Readiness probes for Decision Central OpenShift Image deployment failed

- templates/rhdm71-full.yaml
Cherry pick of #85
Signed-off-by: Jakub Schwan jschwan@redhat.com
> [7.1.x] [RHDM-706] Liveness and Readiness probes for Decision Central OpenShift Image deployment failed

- .gitignore
> [RHDM-697] make .gitignore ignore any "my" .yaml file

- rhdm71-image-streams.yaml
> update imagestreams to registry.redhat.io

- optaweb/README.adoc
- optaweb/image.yaml
- templates/rhdm70-optaweb-externaldb.yaml
Signed-off-by: calvin zhu <calvinzhu@hotmail.com>
> add optaweb openshift image and template, switch to rhdm71-dev

- templates/rhdm70-full.yaml
- templates/rhdm70-kieserver-basic-s2i.yaml
- templates/rhdm70-kieserver-https-s2i.yaml
- templates/rhdm70-kieserver.yaml
> [RHDM-689] - Improve the template message

- templates/rhdm71-full.yaml
- templates/rhdm71-kieserver-basic-s2i.yaml
- templates/rhdm71-kieserver-https-s2i.yaml
- templates/rhdm71-kieserver.yaml
- templates/rhdm71-optaweb-externaldb.yaml
> [RHDM-716] - Standardize application templates

- decisioncentral/cp-overrides.yaml
- decisioncentral/rel-overrides.yaml
- kieserver/cp-overrides.yaml
- kieserver/rel-overrides.yaml
[RHDM-691] update to CE sprint-23 branch to get CLOUD-2722 changes needed by RHDM-691
https://issues.jboss.org/browse/RHDM-691
> [RHDM-691] update to CE sprint-23 branch to get CLOUD-2722 changes needed by RHDM-691

- decisioncentral/image.yaml
- templates/rhdm71-full.yaml
[RHDM-722] fix git hooks dir
https://issues.jboss.org/browse/RHDM-722
> [RHDM-722] fix git hooks dir

- optaweb/cp-overrides.yaml
- optaweb/dev-overrides.yaml
- optaweb/image.yaml
- optaweb/rel-overrides.yaml
- rhdm71-image-streams.yaml
- templates/rhdm71-optaweb-externaldb.yaml
[RHDM-697] including optaweb image in build alignment
https://issues.jboss.org/browse/RHDM-697
> [RHDM-697] including optaweb image in build alignment

- templates/rhdm71-optaweb-employee-rostering-externaldb.yaml
> [RHDM-727] fix 70 to 71 typo in template

- controller/README.adoc
- controller/cp-overrides.yaml
- controller/dev-overrides.yaml
- controller/image.yaml
- controller/rel-overrides.yaml
- decisioncentral-indexing/cp-overrides.yaml
- decisioncentral-indexing/dev-overrides.yaml
- decisioncentral-indexing/image.yaml
- decisioncentral-indexing/rel-overrides.yaml
- rhdm71-image-streams.yaml
[RHDM-718] Update RHDM binaries in images from 7.0.1 to 7.1.0
https://issues.jboss.org/browse/RHDM-718
> [RHDM-718] Update RHDM binaries in images from 7.0.1 to 7.1.0

- templates/rhdm71-optaweb-employee-rostering-externaldb.yaml
> adjust template description e doc annotations

- controller/image.yaml
- decisioncentral-indexing/image.yaml
- decisioncentral/image.yaml
- kieserver/image.yaml
- optaweb-employee-rostering/image.yaml
> [RHDM-691] fix back to sprint-23 of CE and EAP

- optaweb-employee-rostering/image.yaml
https://issues.jboss.org/browse/RHDM-727
> [RHDM-727] remove s2i

- templates/rhdm71-kieserver.yaml
- templates/rhdm71-prod-immutable-kieserver.yaml
Signed-off-by: Karel Suta <ksuta@redhat.com>
> [KIECLOUD-10] Remove unused template properties

- templates/rhdm71-authoring-ha.yaml
> [KIECLOUD-10] - Unused properties in templates and missing labels

- .gitignore
KIECLOUD-12: add my*.json to .gitignore in addition to my*.yaml in RHDM/RHPAM
https://issues.jboss.org/browse/KIECLOUD-12
> KIECLOUD-12: add my*.json to .gitignore in addition to my*.yaml in RHDM/RHPAM

- templates/rhdm71-trial-ephemeral.yaml
[RHDM-520] Provide CORS configuration support for Kie Server in RHDM
https://issues.jboss.org/browse/RHDM-520
> [RHDM-520] Provide CORS configuration support for Kie Server in RHDM

- .circleci/config.yml
- templates/README.md
> prepare for circle ci integration

- controller/cp-overrides.yaml
- controller/image.yaml
- controller/rel-overrides.yaml
- decisioncentral-indexing/cp-overrides.yaml
- decisioncentral-indexing/image.yaml
- decisioncentral-indexing/rel-overrides.yaml
- decisioncentral/cp-overrides.yaml
- decisioncentral/image.yaml
- decisioncentral/rel-overrides.yaml
- kieserver/cp-overrides.yaml
- kieserver/image.yaml
- kieserver/rel-overrides.yaml
- optaweb-employee-rostering/cp-overrides.yaml
- optaweb-employee-rostering/image.yaml
- optaweb-employee-rostering/rel-overrides.yaml
[RHDM-762] Update CE Sprint from 23 to 24 in RHDM
https://issues.jboss.org/browse/RHDM-762
> [RHDM-762] Update CE Sprint from 23 to 24 in RHDM

- rhdm72-image-streams.yaml
[RHDM-763] Update versions in images, streams, templates, & docs from 7.1 to 7.2 in RHDM
https://issues.jboss.org/browse/RHDM-763
> [RHDM-763] Update versions in images, streams, templates, & docs from 7.1 to 7.2 in RHDM

- controller/cp-overrides.yaml
- controller/image.yaml
- controller/rel-overrides.yaml
- decisioncentral-indexing/cp-overrides.yaml
- decisioncentral-indexing/image.yaml
- decisioncentral-indexing/rel-overrides.yaml
- decisioncentral/cp-overrides.yaml
- decisioncentral/image.yaml
- decisioncentral/rel-overrides.yaml
- kieserver/cp-overrides.yaml
- kieserver/image.yaml
- kieserver/rel-overrides.yaml
- optaweb-employee-rostering/cp-overrides.yaml
- optaweb-employee-rostering/image.yaml
- optaweb-employee-rostering/rel-overrides.yaml
- rhdm71-image-streams.yaml
- templates/docs/rhdm71-authoring-ha.adoc
- templates/docs/rhdm71-authoring.adoc
- templates/docs/rhdm71-kieserver.adoc
- templates/docs/rhdm71-prod-immutable-kieserver.adoc
- templates/docs/rhdm71-trial-ephemeral.adoc
- templates/optaweb/rhdm71-optaweb-employee-rostering-trial-ephemeral.yaml
- templates/rhdm71-authoring-ha.yaml
- templates/rhdm71-authoring.yaml
- templates/rhdm71-kieserver.yaml
- templates/rhdm71-prod-immutable-kieserver.yaml
- templates/rhdm71-trial-ephemeral.yaml
[RHDM-767] Update versions in images, streams, templates, & docs from 7.1 to 7.1.1 in RHDM
https://issues.jboss.org/browse/RHDM-767
> [RHDM-767] Update versions in images, streams, templates, & docs from 7.1 to 7.1.1 in RHDM

- ce.yaml
- controller/image.yaml
- decisioncentral-indexing/image.yaml
- decisioncentral/image.yaml
- kieserver/image.yaml
- optaweb-employee-rostering/image.yaml
[RHDM-768] Integrate RHDM with new engineering CI system
https://issues.jboss.org/browse/RHDM-768
> [RHDM-768] Integrate RHDM with new engineering CI system

- controller/cp-overrides.yaml
- controller/image.yaml
- controller/rel-overrides.yaml
- decisioncentral-indexing/cp-overrides.yaml
- decisioncentral-indexing/image.yaml
- decisioncentral-indexing/rel-overrides.yaml
- decisioncentral/cp-overrides.yaml
- decisioncentral/image.yaml
- decisioncentral/rel-overrides.yaml
- kieserver/cp-overrides.yaml
- kieserver/image.yaml
- kieserver/rel-overrides.yaml
- optaweb-employee-rostering/cp-overrides.yaml
- optaweb-employee-rostering/image.yaml
- optaweb-employee-rostering/rel-overrides.yaml
[RHDM-763] correct versions
https://issues.jboss.org/browse/RHDM-763
> [RHDM-763] correct versions

- templates/docs/rhdm72-authoring-ha.adoc
- templates/rhdm72-authoring-ha.yaml
[KIECLOUD-29] Update RHDM and RHPAM AMQ broker from 7.1 to 7.2
https://issues.jboss.org/browse/KIECLOUD-29
> [KIECLOUD-29] Update RHDM and RHPAM AMQ broker from 7.1 to 7.2

- controller/cp-overrides.yaml
- controller/dev-overrides.yaml
- controller/image.yaml
- controller/rel-overrides.yaml
- decisioncentral-indexing/cp-overrides.yaml
- decisioncentral-indexing/dev-overrides.yaml
- decisioncentral-indexing/image.yaml
- decisioncentral-indexing/rel-overrides.yaml
- decisioncentral/cp-overrides.yaml
- decisioncentral/dev-overrides.yaml
- decisioncentral/image.yaml
- decisioncentral/rel-overrides.yaml
- kieserver/cp-overrides.yaml
- kieserver/dev-overrides.yaml
- kieserver/image.yaml
- kieserver/rel-overrides.yaml
- optaweb-employee-rostering/cp-overrides.yaml
- optaweb-employee-rostering/dev-overrides.yaml
- optaweb-employee-rostering/image.yaml
- optaweb-employee-rostering/rel-overrides.yaml
- templates/rhdm72-authoring-ha.yaml
- templates/rhdm72-authoring.yaml
- templates/rhdm72-kieserver.yaml
- templates/rhdm72-prod-immutable-kieserver.yaml
- templates/rhdm72-trial-ephemeral.yaml
[KIECLOUD-20] Update RHDM and RHPAM images to be based on EAP 7.2.x image
> [KIECLOUD-20] Update RHDM and RHPAM images to be based on EAP 7.2.x image

- templates/rhdm72-authoring-ha.yaml
- templates/rhdm72-authoring.yaml
- templates/rhdm72-kieserver.yaml
- templates/rhdm72-prod-immutable-kieserver.yaml
- templates/rhdm72-trial-ephemeral.yaml
[KIECLOUD-20] revert to external route for org.kie.server.location
> [KIECLOUD-20] revert to external route for org.kie.server.location

- templates/optaweb/rhdm72-optaweb-employee-rostering-externaldb.yaml
[RHDM-764] revert addition of optaweb extension image
> [RHDM-764] revert addition of optaweb extension image

- controller/image.yaml
- decisioncentral-indexing/image.yaml
- decisioncentral/image.yaml
- kieserver/image.yaml
- optaweb-employee-rostering/image.yaml
[KIECLOUD-33] fix repository references in RHDM image.yaml files
https://issues.jboss.org/browse/KIECLOUD-33
> [KIECLOUD-33] fix repository references in RHDM image.yaml files

- controller/dev-overrides.yaml
- decisioncentral/dev-overrides.yaml
- kieserver/dev-overrides.yaml
- optaweb-employee-rostering/dev-overrides.yaml
[KIECLOUD-20] switch to EAP72-RC1
> [KIECLOUD-20] switch to EAP72-RC1

- controller/cp-overrides.yaml
- controller/dev-overrides.yaml
- controller/image.yaml
- controller/rel-overrides.yaml
- decisioncentral-indexing/cp-overrides.yaml
- decisioncentral-indexing/dev-overrides.yaml
- decisioncentral-indexing/image.yaml
- decisioncentral-indexing/rel-overrides.yaml
- decisioncentral/cp-overrides.yaml
- decisioncentral/dev-overrides.yaml
- decisioncentral/image.yaml
- decisioncentral/rel-overrides.yaml
- kieserver/cp-overrides.yaml
- kieserver/dev-overrides.yaml
- kieserver/image.yaml
- kieserver/rel-overrides.yaml
- optaweb-employee-rostering/cp-overrides.yaml
- optaweb-employee-rostering/dev-overrides.yaml
- optaweb-employee-rostering/image.yaml
- optaweb-employee-rostering/rel-overrides.yaml
Signed-off-by: Piotr Szubiakowski <pszubiak@redhat.com>
> BXMSPROD-207 resign from -dev and -cp branches in dist-git.

- controller/container.yaml
- controller/content_sets.yml
- controller/dev-overrides.yaml
- controller/image.yaml
- controller/rel-overrides.yaml
- decisioncentral-indexing/container.yaml
- decisioncentral-indexing/content_sets.yml
- decisioncentral-indexing/dev-overrides.yaml
- decisioncentral-indexing/image.yaml
- decisioncentral-indexing/rel-overrides.yaml
- decisioncentral/container.yaml
- decisioncentral/content_sets.yml
- decisioncentral/dev-overrides.yaml
- decisioncentral/image.yaml
- decisioncentral/rel-overrides.yaml
- kieserver/container.yaml
- kieserver/content_sets.yml
- kieserver/dev-overrides.yaml
- kieserver/image.yaml
- kieserver/rel-overrides.yaml
- optaweb-employee-rostering/container.yaml
- optaweb-employee-rostering/content_sets.yml
- optaweb-employee-rostering/dev-overrides.yaml
- optaweb-employee-rostering/image.yaml
- optaweb-employee-rostering/rel-overrides.yaml
[KIECLOUD-50] Update RHDM and RHPAM images for use with cekit 2.2.1 (master)
https://issues.jboss.org/browse/KIECLOUD-50
> [KIECLOUD-50] Update RHDM and RHPAM images for use with cekit 2.2.1 (master)

- controller/container.yaml
- controller/content_sets.yml
- controller/dev-overrides.yaml
- controller/image.yaml
- controller/rel-overrides.yaml
- decisioncentral-indexing/container.yaml
- decisioncentral-indexing/content_sets.yml
- decisioncentral-indexing/dev-overrides.yaml
- decisioncentral-indexing/image.yaml
- decisioncentral-indexing/rel-overrides.yaml
- decisioncentral/container.yaml
- decisioncentral/content_sets.yml
- decisioncentral/dev-overrides.yaml
- decisioncentral/image.yaml
- decisioncentral/rel-overrides.yaml
- kieserver/container.yaml
- kieserver/content_sets.yml
- kieserver/dev-overrides.yaml
- kieserver/image.yaml
- kieserver/rel-overrides.yaml
- optaweb-employee-rostering/container.yaml
- optaweb-employee-rostering/content_sets.yml
- optaweb-employee-rostering/dev-overrides.yaml
- optaweb-employee-rostering/image.yaml
- optaweb-employee-rostering/rel-overrides.yaml
[KIECLOUD-50] Update RHDM and RHPAM images for use with cekit 2.2.1 (7.2.x)
https://issues.jboss.org/browse/KIECLOUD-50
> [KIECLOUD-50] Update RHDM and RHPAM images for use with cekit 2.2.1 (7.2.x)

- controller/container.yaml
- controller/content_sets.yml
- decisioncentral-indexing/container.yaml
- decisioncentral-indexing/content_sets.yml
- decisioncentral/container.yaml
- decisioncentral/content_sets.yml
- kieserver/container.yaml
- kieserver/content_sets.yml
- optaweb-employee-rostering/container.yaml
- optaweb-employee-rostering/content_sets.yml
[KIECLOUD-66] ppc64le should not be included in container.yaml and content_sets.yml files
https://issues.jboss.org/browse/KIECLOUD-66
> [KIECLOUD-66] ppc64le should not be included in container.yaml and content_sets.yml files

- controller/dev-overrides.yaml
- decisioncentral/dev-overrides.yaml
- kieserver/dev-overrides.yaml
- optaweb-employee-rostering/dev-overrides.yaml
- templates/rhdm72-authoring-ha.yaml
[KIECLOUD-70] Update images to align with EAP72-CR2-1
https://issues.jboss.org/browse/KIECLOUD-70
> [KIECLOUD-70] Update images to align with EAP72-CR2-1

- templates/optaweb/rhdm72-optaweb-employee-rostering-trial-ephemeral.yaml
- templates/rhdm72-authoring-ha.yaml
- templates/rhdm72-authoring.yaml
- templates/rhdm72-kieserver.yaml
- templates/rhdm72-prod-immutable-kieserver.yaml
- templates/rhdm72-trial-ephemeral.yaml
> [BXMSDOC-3456] - RHDM template review by tech writer (7.2.x)

- templates/optaweb/rhdm72-optaweb-employee-rostering-externaldb.yaml
- templates/optaweb/rhdm72-optaweb-employee-rostering-mysql.yaml
- templates/optaweb/rhdm72-optaweb-employee-rostering-postgresql.yaml
- templates/optaweb/rhdm72-optaweb-employee-rostering-trial-ephemeral.yaml
- templates/rhdm72-authoring-ha.yaml
- templates/rhdm72-authoring.yaml
- templates/rhdm72-kieserver.yaml
- templates/rhdm72-prod-immutable-kieserver.yaml
- templates/rhdm72-trial-ephemeral.yaml
> [BXMSDOC-3456] - RHDM template review by tech writer (master)

- controller/dev-overrides.yaml
- decisioncentral/dev-overrides.yaml
- kieserver/dev-overrides.yaml
- optaweb-employee-rostering/dev-overrides.yaml
[KIECLOUD-20] update EAP 7.2 to CR3
> [KIECLOUD-20] update EAP 7.2 to CR3

- controller/dev-overrides.yaml
- decisioncentral/dev-overrides.yaml
- kieserver/dev-overrides.yaml
- optaweb-employee-rostering/dev-overrides.yaml
[KIECLOUD-20] update EAP 7.2 to CR4
> [KIECLOUD-20] update EAP 7.2 to CR4

- rhdm73-image-streams.yaml
> [KIECLOUD-82] - Update ImageStreams Kind

- controller/dev-overrides.yaml
- decisioncentral/dev-overrides.yaml
- kieserver/dev-overrides.yaml
- optaweb-employee-rostering/dev-overrides.yaml
[KIECLOUD-20] Upgrade EAP to 7.2 CR5
> [KIECLOUD-20] Upgrade EAP to 7.2 CR5

- rhdm73-image-streams.yaml
https://issues.jboss.org/browse/KIECLOUD-100
> [KIECLOUD-100] Fix a description of the Optaweb Employee Rostering app

- templates/docs/README.adoc
- templates/docs/rhdm72-authoring-ha.adoc
> [KIECLOUD-112] - Task, regenerated template docs

- templates/rhdm73-authoring-ha.yaml
JIRA Link: https://issues.jboss.org/browse/RHDM-847
* Added Additional Role and RoleBinding objects
* Added scaledown-controller for scale down events
* Required to add view role to default service account
(oc policy add-role-to-user view -z default)
Signed-off-by: rimolive <ricardo.martinelli.oliveira@gmail.com>
> [RHDM-847] Change AMQ deployment to HA

- decisioncentral-indexing/content_sets.yml
[RHPAM-1832] Several images fail content set testing
https://issues.jboss.org/browse/RHPAM-1832
> [RHPAM-1832] Several images fail content set testing

- templates/rhdm73-authoring-ha.yaml
- templates/rhdm73-authoring.yaml
[KIECLOUD-123] expose MAVEN_MIRROR_URL parameter in authoring templates
https://issues.jboss.org/browse/KIECLOUD-123
> [KIECLOUD-123] expose MAVEN_MIRROR_URL parameter in authoring templates

- templates/rhdm73-authoring.yaml
- templates/rhdm73-trial-ephemeral.yaml
[RHDM-861] Decision central liveness and readiness probes point to wrong URL
https://issues.jboss.org/browse/RHDM-861
> [RHDM-861] Decision central liveness and readiness probes point to wrong URL

- controller/image.yaml
- controller/tag-overrides.yaml
- decisioncentral-indexing/image.yaml
- decisioncentral-indexing/tag-overrides.yaml
- decisioncentral/image.yaml
- decisioncentral/tag-overrides.yaml
- kieserver/image.yaml
- kieserver/tag-overrides.yaml
- optaweb-employee-rostering/image.yaml
- optaweb-employee-rostering/tag-overrides.yaml
- rhdm73-image-streams.yaml
- templates/rhdm73-authoring-ha.yaml
- templates/rhdm73-authoring.yaml
- templates/rhdm73-kieserver.yaml
- templates/rhdm73-optaweb-employee-rostering.yaml
- templates/rhdm73-prod-immutable-kieserver.yaml
- templates/rhdm73-trial-ephemeral.yaml
[KIECLOUD-175] prepare 7.3.x branches for 7.3.1
https://issues.jboss.org/browse/KIECLOUD-175
> [KIECLOUD-175] prepare 7.3.x branches for 7.3.1

- templates/rhdm74-prod-immutable-kieserver-amq.yaml
Updating the AMQ template accordingly
https://issues.jboss.org/browse/KIECLOUD-180
> [KIECLOUD-180] Immutable Kieserver AMQ templates have incorrect naming

- controller/branch-overrides.yaml
- controller/image.yaml
- controller/tag-overrides.yaml
- decisioncentral-indexing/branch-overrides.yaml
- decisioncentral-indexing/tag-overrides.yaml
- decisioncentral/branch-overrides.yaml
- decisioncentral/image.yaml
- decisioncentral/tag-overrides.yaml
- kieserver/branch-overrides.yaml
- kieserver/image.yaml
- kieserver/tag-overrides.yaml
- optaweb-employee-rostering/branch-overrides.yaml
- optaweb-employee-rostering/image.yaml
- optaweb-employee-rostering/tag-overrides.yaml
- templates/rhdm74-authoring-ha-datagrid.yaml
- templates/rhdm74-authoring-ha.yaml
- templates/rhdm74-authoring.yaml
- templates/rhdm74-kieserver.yaml
- templates/rhdm74-prod-immutable-kieserver-amq.yaml
- templates/rhdm74-prod-immutable-kieserver.yaml
- templates/rhdm74-trial-ephemeral.yaml
[KIECLOUD-176] Update RHDM and RHPAM dependency references and versions
https://issues.jboss.org/browse/KIECLOUD-176
> [KIECLOUD-176] Update RHDM and RHPAM dependency references and versions

- .gitignore
- quickstarts/hello-rules-multi-module/README.md
- quickstarts/hello-rules-multi-module/hellorules-model/pom.xml
- quickstarts/hello-rules-multi-module/hellorules/pom.xml
- quickstarts/hello-rules-multi-module/pom.xml
- quickstarts/hello-rules/README.md
- quickstarts/hello-rules/hellorules-client/pom.xml
- quickstarts/hello-rules/hellorules-client/src/main/java/org/openshift/quickstarts/rhdm/kieserver/hellorules/client/HelloRulesClient.java
- quickstarts/hello-rules/hellorules/pom.xml
- quickstarts/hello-rules/pom.xml
- templates/rhdm74-kieserver.yaml
- templates/rhdm74-prod-immutable-kieserver-amq.yaml
- templates/rhdm74-prod-immutable-kieserver.yaml
Signed-off-by: Ricardo Zanini <zanini@redhat.com>
> [KIECLOUD-181] Add JDK 11 compatibility with quickstarter

- controller/artifact-overrides.yaml
- controller/branch-overrides.yaml
- controller/tag-overrides.yaml
- decisioncentral-indexing/branch-overrides.yaml
- decisioncentral-indexing/tag-overrides.yaml
- decisioncentral/artifact-overrides.yaml
- decisioncentral/branch-overrides.yaml
- decisioncentral/tag-overrides.yaml
- kieserver/artifact-overrides.yaml
- kieserver/branch-overrides.yaml
- kieserver/tag-overrides.yaml
- optaweb-employee-rostering/artifact-overrides.yaml
- optaweb-employee-rostering/branch-overrides.yaml
- optaweb-employee-rostering/tag-overrides.yaml
[BAPL-1072] Cloud product build pipeline improvements
https://issues.jboss.org/browse/BAPL-1072
> [BAPL-1072] Cloud product build pipeline improvements

- controller/artifact-overrides.yaml
- controller/branch-overrides.yaml
- controller/content_sets.yml
- controller/image.yaml
- controller/tag-overrides.yaml
- decisioncentral-indexing/branch-overrides.yaml
- decisioncentral-indexing/content_sets.yml
- decisioncentral-indexing/image.yaml
- decisioncentral-indexing/tag-overrides.yaml
- decisioncentral/artifact-overrides.yaml
- decisioncentral/branch-overrides.yaml
- decisioncentral/content_sets.yml
- decisioncentral/image.yaml
- decisioncentral/tag-overrides.yaml
- kieserver/artifact-overrides.yaml
- kieserver/branch-overrides.yaml
- kieserver/content_sets.yml
- kieserver/image.yaml
- kieserver/tag-overrides.yaml
- optaweb-employee-rostering/artifact-overrides.yaml
- optaweb-employee-rostering/branch-overrides.yaml
- optaweb-employee-rostering/content_sets.yml
- optaweb-employee-rostering/image.yaml
- optaweb-employee-rostering/tag-overrides.yaml
[RHDM-894] Update RHDM images to use RHEL8 (UBI) base layer
https://issues.jboss.org/browse/RHDM-894
> [RHDM-894] Update RHDM images to use RHEL8 (UBI) base layer

- templates/rhdm74-authoring-ha-datagrid.yaml
- templates/rhdm74-authoring-ha.yaml
- templates/rhdm74-authoring.yaml
- templates/rhdm74-kieserver.yaml
- templates/rhdm74-prod-immutable-kieserver-amq.yaml
- templates/rhdm74-prod-immutable-kieserver.yaml
- templates/rhdm74-trial-ephemeral.yaml
[KIECLOUD-107] Add Prometheus config to EAP-based RHDM and RHPAM 7 images
https://issues.jboss.org/browse/KIECLOUD-107
> [KIECLOUD-107] Add Prometheus config to EAP-based RHDM and RHPAM 7 images

- decisioncentral/image.yaml
- kieserver/image.yaml
https://issues.jboss.org/browse/RHPAM-1387
Signed-off-by: Mauricio Magnani <mmagnani@redhat.com>
> [rhpam-1387] Allow set Smart router location to external URL in RHPAM

- decisioncentral/image.yaml
- templates/rhdm74-authoring-ha-datagrid.yaml
- templates/rhdm74-authoring-ha.yaml
- templates/rhdm74-authoring.yaml
- templates/rhdm74-trial-ephemeral.yaml
See:
https://issues.jboss.org/browse/KIECLOUD-217
Signed-off-by: Ricardo Zanini <zanini@redhat.com>
> [KIECLOUD-217] - Kie data path standardization

- templates/rhdm74-authoring-ha-datagrid.yaml
- templates/rhdm74-authoring-ha.yaml
- templates/rhdm74-prod-immutable-kieserver-amq.yaml
[KIECLOUD-221] upgrade datagrid and amq broker versions
https://issues.jboss.org/browse/KIECLOUD-221
> [KIECLOUD-221] upgrade datagrid and amq broker versions

- controller/image.yaml
- decisioncentral-indexing/image.yaml
- decisioncentral/image.yaml
- kieserver/image.yaml
- optaweb-employee-rostering/image.yaml
[RHDM-894] fix osbs repo branch suffix per release guidelines
https://issues.jboss.org/browse/RHDM-894
> [RHDM-894] fix osbs repo branch suffix per release guidelines

- templates/rhdm74-authoring-ha.yaml
- templates/rhdm74-authoring.yaml
- templates/rhdm74-kieserver.yaml
- templates/rhdm74-prod-immutable-kieserver-amq.yaml
- templates/rhdm74-prod-immutable-kieserver.yaml
- templates/rhdm74-trial-ephemeral.yaml
Propagate OpenShift enhancement related changes from RHPAM to RHDM
Related PRs
https://github.com/jboss-container-images/jboss-kie-modules/pull/214
https://github.com/jboss-container-images/rhpam-7-openshift-image/pull/285
https://github.com/jboss-container-images/rhpam-7-openshift-image/pull/307
> [BAPL-1302] OpenShift-specific architectural improvements - RHDM OpenShift Enhancement (In-sync with RHPAM)

- controller/branch-overrides.yaml
- controller/image.yaml
- controller/tag-overrides.yaml
- decisioncentral-indexing/branch-overrides.yaml
- decisioncentral-indexing/image.yaml
- decisioncentral-indexing/tag-overrides.yaml
- decisioncentral/branch-overrides.yaml
- decisioncentral/image.yaml
- decisioncentral/tag-overrides.yaml
- kieserver/branch-overrides.yaml
- kieserver/image.yaml
- kieserver/tag-overrides.yaml
- optaweb-employee-rostering/branch-overrides.yaml
- optaweb-employee-rostering/image.yaml
- optaweb-employee-rostering/tag-overrides.yaml
[RHDM-894] fix osbs repo branch suffix per clarified release guidelines
https://issues.jboss.org/browse/RHDM-894
> [RHDM-894] fix osbs repo branch suffix per clarified release guidelines

- controller/artifact-overrides.yaml
- controller/branch-overrides.yaml
- controller/tag-overrides.yaml
- decisioncentral/artifact-overrides.yaml
- decisioncentral/branch-overrides.yaml
- decisioncentral/tag-overrides.yaml
- kieserver/artifact-overrides.yaml
- kieserver/branch-overrides.yaml
- kieserver/tag-overrides.yaml
- optaweb-employee-rostering/artifact-overrides.yaml
- optaweb-employee-rostering/branch-overrides.yaml
- optaweb-employee-rostering/tag-overrides.yaml
[KIECLOUD-236] align RHDM 7.4.0 images with appropriate EAP 7.2.1 tags
https://issues.jboss.org/browse/KIECLOUD-236
> [KIECLOUD-236] align RHDM 7.4.0 images with appropriate EAP 7.2.1 tags

- templates/docs/rhdm74-authoring-ha.adoc
- templates/rhdm74-authoring-ha.yaml
- templates/rhdm74-prod-immutable-kieserver-amq.yaml
See: https://issues.jboss.org/browse/KIECLOUD-232
Signed-off-by: Mauricio Magnani <mmagnani@redhat.com>
> [KIECLOUD-232] - Update images of "amq-broker" to version 7.3

- templates/rhdm74-authoring-ha.yaml
- templates/rhdm74-authoring.yaml
- templates/rhdm74-kieserver.yaml
- templates/rhdm74-prod-immutable-kieserver-amq.yaml
- templates/rhdm74-prod-immutable-kieserver.yaml
- templates/rhdm74-trial-ephemeral.yaml
a) Remove "KIE_SERVER_USE_SECURE_ROUTE_NAME"
b) Remove "secure-" prefix from templates and change to base name for https routes
c) Add "insecure-" prefix http routes
> [KIECLOUD-97] Synchronize OpenShiftStartupStrategy related changes between Template, APB, and Operator

- templates/rhdm75-optaweb-employee-rostering.yaml
Signed-off-by: Ricardo Zanini <zanini@redhat.com>
See:
https://issues.jboss.org/browse/RHDM-997
> [RHDM-997] - Setting XA Datasource Postgres variable names (7.5.x)

- templates/rhdm74-optaweb-employee-rostering.yaml
Signed-off-by: Ricardo Zanini <zanini@redhat.com>
See:
https://issues.jboss.org/browse/RHDM-997
Will cherry pick to master as soon as this gets approved
> [RHDM-997] - Setting XA Datasource Postgres variable names

- templates/rhdm74-prod-immutable-kieserver-amq.yaml
> [KIECLOUD-122] - Enable JMS for RHDM and RHPAM images.

- templates/rhdm75-authoring-ha.yaml
- templates/rhdm75-authoring.yaml
- templates/rhdm75-trial-ephemeral.yaml
See:
https://issues.jboss.org/browse/KIECLOUD-160
> KIECLOUD-160 removing git ports

- templates/rhdm75-authoring-ha.yaml
- templates/rhdm75-authoring.yaml
- templates/rhdm75-kieserver.yaml
- templates/rhdm75-prod-immutable-kieserver-amq.yaml
- templates/rhdm75-prod-immutable-kieserver.yaml
- templates/rhdm75-trial-ephemeral.yaml
https://issues.jboss.org/browse/KIECLOUD-276
@errantepiphany Can you please take a look?
Signed-off-by: Karel Suta <ksuta@redhat.com>
> [KIECLOUD-276] Adjust readiness probe parameters

- templates/rhdm75-authoring-ha.yaml
- templates/rhdm75-authoring.yaml
[RHPAM-2282] Changes in users and roles made by Business central are not persisted
https://issues.jboss.org/browse/RHPAM-2282
> [RHPAM-2282] Changes in users and roles made by Business central are not persisted

- templates/rhdm75-authoring.yaml
[RHPAM-2314] Strategy and Access Mode corrections
https://issues.jboss.org/browse/RHPAM-2314
> [RHPAM-2314] Strategy and Access Mode corrections

- templates/rhdm75-authoring-ha.yaml
> [RHDM-1057] - Review and update Authoring HA template for latest changes

- controller/branch-overrides.yaml
- controller/image.yaml
- controller/tag-overrides.yaml
- decisioncentral/branch-overrides.yaml
- decisioncentral/image.yaml
- decisioncentral/tag-overrides.yaml
- kieserver/branch-overrides.yaml
- kieserver/tag-overrides.yaml
- optaweb-employee-rostering/branch-overrides.yaml
- optaweb-employee-rostering/image.yaml
- optaweb-employee-rostering/tag-overrides.yaml
[KIECLOUD-313] upgrade EAP from 7.2.1 to 7.2.3
https://issues.jboss.org/browse/KIECLOUD-313
> [KIECLOUD-313] upgrade EAP from 7.2.1 to 7.2.3

- templates/rhdm75-prod-immutable-kieserver-amq.yaml
> Update AMQ image version for kieserver jms integration

- templates/docs/rhdm75-trial-ephemeral.adoc
> [ADOCS_REGEN] regenerate adocs per recent changes

- controller/image.yaml
- controller/osbs-extra/gating.yaml
- decisioncentral/image.yaml
- decisioncentral/osbs-extra/gating.yaml
- kieserver/image.yaml
- kieserver/osbs-extra/gating.yaml
Signed-off-by: Jakub Schwan <jschwan@redhat.com>
> [7.5.x] Adding gating.yaml file for CVP to be persisted in dist-git repo

- controller/image.yaml
- controller/osbs-extra/gating.yaml
- decisioncentral/image.yaml
- decisioncentral/osbs-extra/gating.yaml
- kieserver/image.yaml
- kieserver/osbs-extra/gating.yaml
Signed-off-by: Jakub Schwan <jschwan@redhat.com>
> Adding gating.yaml file for CVP to be persisted in dist-git repo

- controller/artifact-overrides.yaml
- controller/image.yaml
- decisioncentral/artifact-overrides.yaml
- decisioncentral/image.yaml
- kieserver/artifact-overrides.yaml
- kieserver/image.yaml
- optaweb-employee-rostering/artifact-overrides.yaml
- optaweb-employee-rostering/image.yaml
[KIECLOUD-328] required changes to build meta information for CPaaS
https://issues.jboss.org/browse/KIECLOUD-328
> [KIECLOUD-328] required changes to build meta information for CPaaS

- templates/rhdm76-authoring-ha.yaml
- templates/rhdm76-prod-immutable-kieserver-amq.yaml
> [RHPAM-2401] - Change strategy to type Rolling for other BA components

- templates/rhdm76-authoring-ha.yaml
- templates/rhdm76-authoring.yaml
- templates/rhdm76-trial-ephemeral.yaml
> [AF-2240] Modify haproxy timeout in the template

- controller/image.yaml
- decisioncentral/image.yaml
- kieserver/image.yaml
- templates/rhdm76-authoring-ha.yaml
- templates/rhdm76-authoring.yaml
- templates/rhdm76-kieserver.yaml
- templates/rhdm76-prod-immutable-kieserver-amq.yaml
- templates/rhdm76-prod-immutable-kieserver.yaml
- templates/rhdm76-trial-ephemeral.yaml
[KIECLOUD-332] image naming convention changes
https://issues.jboss.org/browse/KIECLOUD-332
> [KIECLOUD-332] image naming convention changes

- controller/image.yaml
- controller/tag-overrides.yaml
- decisioncentral/image.yaml
- decisioncentral/tag-overrides.yaml
- kieserver/image.yaml
- kieserver/tag-overrides.yaml
- optaweb-employee-rostering/image.yaml
- optaweb-employee-rostering/tag-overrides.yaml
- quickstarts/hello-rules-multi-module/README.md
- quickstarts/hello-rules/README.md
- rhdm75-image-streams.yaml
- templates/rhdm75-authoring-ha.yaml
- templates/rhdm75-authoring.yaml
- templates/rhdm75-kieserver.yaml
- templates/rhdm75-optaweb-employee-rostering.yaml
- templates/rhdm75-prod-immutable-kieserver-amq.yaml
- templates/rhdm75-prod-immutable-kieserver.yaml
- templates/rhdm75-trial-ephemeral.yaml
[KIECLOUD-335] Upgrade RHDM and RHPAM cloud images to 7.5.1
https://issues.jboss.org/browse/KIECLOUD-335
> [KIECLOUD-335] Upgrade RHDM and RHPAM cloud images to 7.5.1

- controller/artifact-overrides.yaml
- controller/branch-overrides.yaml
- controller/tag-overrides.yaml
- decisioncentral/artifact-overrides.yaml
- decisioncentral/branch-overrides.yaml
- decisioncentral/tag-overrides.yaml
- kieserver/artifact-overrides.yaml
- kieserver/branch-overrides.yaml
- kieserver/tag-overrides.yaml
[KIECLOUD-337] Upgrade RHDM and RHPAM EAP-based images to EAP 7.2.4
https://issues.jboss.org/browse/KIECLOUD-337
> [KIECLOUD-337] Upgrade RHDM and RHPAM EAP-based images to EAP 7.2.4

- templates/rhdm77-authoring-ha.yaml
- templates/rhdm77-authoring.yaml
- templates/rhdm77-kieserver.yaml
- templates/rhdm77-prod-immutable-kieserver-amq.yaml
- templates/rhdm77-prod-immutable-kieserver.yaml
- templates/rhdm77-trial-ephemeral.yaml
Signed-off-by: Mikhail Ramendik <mramendi@redhat.com>
https://issues.jboss.org/browse/KIECLOUD-346
> [KIECLOUD-346] username to user name and typos - master

- templates/docs/rhdm76-authoring-ha.adoc
- templates/docs/rhdm76-authoring.adoc
- templates/docs/rhdm76-kieserver.adoc
- templates/docs/rhdm76-prod-immutable-kieserver-amq.adoc
- templates/docs/rhdm76-prod-immutable-kieserver.adoc
- templates/docs/rhdm76-trial-ephemeral.adoc
> [KIECLOUD-347] - Re-generated adocs files for branch 7.6.x

- templates/rhdm76-authoring-ha.yaml
Cherry pick of #318 to 7.6.x branch
See: https://issues.redhat.com/browse/RHDM-1192
Signed-off-by: Jakub Schwan <jschwan@redhat.com>
> [RHDM-1192] Increase memory limit for BC in Authoring HA

- controller/artifact-overrides.yaml
- controller/branch-overrides.yaml
- controller/tag-overrides.yaml
- decisioncentral/artifact-overrides.yaml
- decisioncentral/branch-overrides.yaml
- decisioncentral/tag-overrides.yaml
- kieserver/artifact-overrides.yaml
- kieserver/branch-overrides.yaml
- kieserver/tag-overrides.yaml
[KIECLOUD-355] Upgrade RHDM and RHPAM EAP-based images to EAP 7.2.6
https://issues.redhat.com/browse/KIECLOUD-355
> [KIECLOUD-355] Upgrade RHDM and RHPAM EAP-based images to EAP 7.2.6

- decisioncentral/image.yaml
[KIECLOUD-228] Hide ISPN logs
https://issues.redhat.com/browse/KIECLOUD-228
> [KIECLOUD-228] Hide ISPN logs

- templates/rhdm77-authoring-ha.yaml
- templates/rhdm77-authoring.yaml
- templates/rhdm77-kieserver.yaml
- templates/rhdm77-prod-immutable-kieserver-amq.yaml
- templates/rhdm77-prod-immutable-kieserver.yaml
- templates/rhdm77-trial-ephemeral.yaml
Fix https://issues.jboss.org/browse/RHPAM-2175
> [RHPAM-2175] External auth only

- templates/docs/rhdm77-authoring-ha.adoc
- templates/docs/rhdm77-authoring.adoc
- templates/rhdm77-authoring-ha.yaml
- templates/rhdm77-authoring.yaml
Related JIRA
https://issues.redhat.com/projects/RHDM/issues/RHDM-1167
Related PR
https://github.com/jboss-container-images/rhpam-7-openshift-image/pull/412
> [RHDM-1167] Change authoring environment to Controller strategy

- templates/rhdm77-authoring-ha.yaml
- templates/rhdm77-authoring.yaml
- templates/rhdm77-trial-ephemeral.yaml
Minor refactoring
Related JIRAs
https://issues.redhat.com/projects/RHPAM/issues/RHPAM-2657
https://issues.redhat.com/projects/RHPAM/issues/RHPAM-2008
https://issues.redhat.com/browse/JBPM-8585
Prerequisite PRs
kiegroup/kie-wb-common#3139
kiegroup/droolsjbpm-integration#1995
Related PRs
jboss-container-images/jboss-kie-modules#352
https://github.com/jboss-container-images/rhpam-7-openshift-image/pull/414
https://github.com/kiegroup/kie-cloud-operator/pull/353
> [RHPAM-2657] KieServer Scale-Up-From-Zero lifecycle hooks logic broken

- templates/rhdm77-authoring-ha.yaml
- templates/rhdm77-authoring.yaml
- templates/rhdm77-kieserver.yaml
- templates/rhdm77-prod-immutable-kieserver-amq.yaml
- templates/rhdm77-prod-immutable-kieserver.yaml
- templates/rhdm77-trial-ephemeral.yaml
Signed-off-by: Mikhail Ramendik <mramendi@redhat.com>
> [BXMSDOC-5159] Editorial changes to templates

- templates/rhdm77-authoring-ha.yaml
- templates/rhdm77-authoring.yaml
> [RHPAM-2732] Kie Server is not connected to BC in Authoring template

- .circleci/config.yml
- README.md
- controller/README.adoc
- controller/image.yaml
- controller/tag-overrides.yaml
- decisioncentral/README.adoc
- decisioncentral/image.yaml
- decisioncentral/tag-overrides.yaml
- kieserver/README.adoc
- kieserver/image.yaml
- kieserver/tag-overrides.yaml
- quickstarts/hello-rules-multi-module/README.md
- quickstarts/hello-rules/README.md
- rhdm78-image-streams.yaml
- templates/docs/README.adoc
- templates/docs/rhdm78-authoring-ha.adoc
- templates/docs/rhdm78-authoring.adoc
- templates/docs/rhdm78-kieserver.adoc
- templates/docs/rhdm78-prod-immutable-kieserver-amq.adoc
- templates/docs/rhdm78-prod-immutable-kieserver.adoc
- templates/docs/rhdm78-trial-ephemeral.adoc
- templates/rhdm78-authoring-ha.yaml
- templates/rhdm78-authoring.yaml
- templates/rhdm78-kieserver.yaml
- templates/rhdm78-prod-immutable-kieserver-amq.yaml
- templates/rhdm78-prod-immutable-kieserver.yaml
- templates/rhdm78-trial-ephemeral.yaml
[KIECLOUD-370] Bump RHDM an RHPAM versions to 7.8.0 on master branch
https://issues.redhat.com/browse/KIECLOUD-370
> [KIECLOUD-370] Bump RHDM an RHPAM versions to 7.8.0 on master branch

- templates/rhdm78-authoring-ha.yaml
- templates/rhdm78-prod-immutable-kieserver-amq.yaml
> [KIECLOUD-378] - Increase AMQ broker version to 7.6

- templates/rhdm77-authoring-ha.yaml
> [RHDM-1253] - Increase DataGrid 7.3 image tag version to 1.5

- templates/docs/rhdm78-authoring-ha.adoc
- templates/rhdm78-authoring-ha.yaml
> RHPAM-2833: Allow to configure replicas in Authoring HA

- controller/image.yaml
- controller/tag-overrides.yaml
- decisioncentral/image.yaml
- decisioncentral/tag-overrides.yaml
- kieserver/image.yaml
- kieserver/tag-overrides.yaml
- quickstarts/hello-rules-multi-module/README.md
- quickstarts/hello-rules/README.md
- rhdm77-image-streams.yaml
- templates/docs/rhdm77-authoring-ha.adoc
- templates/docs/rhdm77-prod-immutable-kieserver-amq.adoc
- templates/rhdm77-authoring-ha.yaml
- templates/rhdm77-authoring.yaml
- templates/rhdm77-kieserver.yaml
- templates/rhdm77-prod-immutable-kieserver-amq.yaml
- templates/rhdm77-prod-immutable-kieserver.yaml
- templates/rhdm77-trial-ephemeral.yaml
> [KIECLOUD-389] - Prepare RHPAM and RHDM repositories for 7.7.1 release

- controller/artifact-overrides.yaml
- controller/branch-overrides.yaml
- controller/image.yaml
- controller/tag-overrides.yaml
- decisioncentral/artifact-overrides.yaml
- decisioncentral/branch-overrides.yaml
- decisioncentral/image.yaml
- decisioncentral/tag-overrides.yaml
- kieserver/artifact-overrides.yaml
- kieserver/branch-overrides.yaml
- kieserver/image.yaml
- kieserver/tag-overrides.yaml
> [KIECLOUD-377] - Increase EAP in OpenShift images to 7.3.0

- templates/rhdm78-kieserver.yaml
Signed-off-by: Mikhail Ramendik <mramendi@redhat.com>
> [KIECLOUD-401] removing mandatory marker from MAVEN_REPO_URL

- controller/branch-overrides.yaml
- decisioncentral/branch-overrides.yaml
- kieserver/branch-overrides.yaml
> [KIECLOUD-402] - update repo branches

- controller/artifact-overrides.yaml
- controller/branch-overrides.yaml
- controller/tag-overrides.yaml
- decisioncentral/artifact-overrides.yaml
- decisioncentral/branch-overrides.yaml
- decisioncentral/tag-overrides.yaml
- kieserver/artifact-overrides.yaml
- kieserver/branch-overrides.yaml
- kieserver/tag-overrides.yaml
> [RHPAM-3016] - Rebuild new 7.7.1 images with EAP 7.2.9

- templates/docs/README.adoc
- templates/docs/rhdm79-authoring-ha.adoc
- templates/docs/rhdm79-authoring.adoc
- templates/docs/rhdm79-kieserver.adoc
- templates/docs/rhdm79-prod-immutable-kieserver-amq.adoc
- templates/docs/rhdm79-prod-immutable-kieserver.adoc
- templates/docs/rhdm79-trial-ephemeral.adoc
> [KIECLOUD-411] - Update adocs

- controller/artifact-overrides.yaml
- controller/branch-overrides.yaml
- controller/tag-overrides.yaml
- decisioncentral/artifact-overrides.yaml
- decisioncentral/branch-overrides.yaml
- decisioncentral/tag-overrides.yaml
- kieserver/artifact-overrides.yaml
- kieserver/branch-overrides.yaml
- kieserver/tag-overrides.yaml
> [RHDM-1429] - Update EAP version from 7.3.1 to 7.3.2 on PAM/DM 7.8.x

- controller/image.yaml
- controller/tag-overrides.yaml
- decisioncentral/image.yaml
- decisioncentral/tag-overrides.yaml
- kieserver/image.yaml
- kieserver/tag-overrides.yaml
- quickstarts/hello-rules-multi-module/README.md
- quickstarts/hello-rules/README.md
- rhdm78-image-streams.yaml
- templates/docs/rhdm78-authoring-ha.adoc
- templates/docs/rhdm78-authoring.adoc
- templates/docs/rhdm78-kieserver.adoc
- templates/docs/rhdm78-prod-immutable-kieserver-amq.adoc
- templates/docs/rhdm78-prod-immutable-kieserver.adoc
- templates/docs/rhdm78-trial-ephemeral.adoc
- templates/rhdm78-authoring-ha.yaml
- templates/rhdm78-authoring.yaml
- templates/rhdm78-kieserver.yaml
- templates/rhdm78-prod-immutable-kieserver-amq.yaml
- templates/rhdm78-prod-immutable-kieserver.yaml
- templates/rhdm78-trial-ephemeral.yaml
> [RHDM-1431] - Build RHDM 7.8.1 Images

- templates/rhdm79-authoring-ha.yaml
> [KIECLOUD-414] - Increase DataGrid 7.3 image tag version to 1.6

- example-credentials.yaml
- quickstarts/hello-rules-multi-module/README.md
- quickstarts/hello-rules-multi-module/hellorules-model/pom.xml
- quickstarts/hello-rules-multi-module/pom.xml
- quickstarts/hello-rules/README.md
- quickstarts/hello-rules/hellorules-client/pom.xml
- quickstarts/hello-rules/hellorules/pom.xml
- quickstarts/hello-rules/pom.xml
> [KIECLOUD-427] - Update RHPAM and RHDM repositories for 7.8.1.GA release

- controller/tag-overrides.yaml
- decisioncentral/tag-overrides.yaml
- kieserver/tag-overrides.yaml
> [KIECLOUD-431] - Prepare branch 7.8.x for new tag 7.8.1.GA-1

- controller/branch-overrides.yaml
- decisioncentral/branch-overrides.yaml
- kieserver/branch-overrides.yaml
- templates/docs/README.adoc
- templates/docs/rhdm79-authoring-ha.adoc
- templates/docs/rhdm79-authoring.adoc
- templates/docs/rhdm79-kieserver.adoc
- templates/docs/rhdm79-prod-immutable-kieserver-amq.adoc
- templates/docs/rhdm79-prod-immutable-kieserver.adoc
- templates/docs/rhdm79-trial-ephemeral.adoc
> [KIECLOUD] - Prepare RHPAM and RHDM repositories for 7.9.0 release

- .circleci/config.yml
- README.md
- controller/README.adoc
- controller/image.yaml
- controller/tag-overrides.yaml
- decisioncentral/README.adoc
- decisioncentral/image.yaml
- decisioncentral/tag-overrides.yaml
- kieserver/README.adoc
- kieserver/image.yaml
- kieserver/tag-overrides.yaml
- quickstarts/hello-rules-multi-module/README.md
- quickstarts/hello-rules/README.md
- rhdm710-image-streams.yaml
- templates/docs/README.adoc
- templates/docs/rhdm710-authoring-ha.adoc
- templates/docs/rhdm710-authoring.adoc
- templates/docs/rhdm710-kieserver.adoc
- templates/docs/rhdm710-prod-immutable-kieserver-amq.adoc
- templates/docs/rhdm710-prod-immutable-kieserver.adoc
- templates/docs/rhdm710-trial-ephemeral.adoc
- templates/rhdm710-authoring-ha.yaml
- templates/rhdm710-authoring.yaml
- templates/rhdm710-kieserver.yaml
- templates/rhdm710-prod-immutable-kieserver-amq.yaml
- templates/rhdm710-prod-immutable-kieserver.yaml
- templates/rhdm710-trial-ephemeral.yaml
> [KIECLOUD-446] - Prepare RHPAM and RHDM master branch for next release

- templates/rhdm79-authoring-ha.yaml
- templates/rhdm79-authoring.yaml
- templates/rhdm79-kieserver.yaml
- templates/rhdm79-prod-immutable-kieserver-amq.yaml
- templates/rhdm79-prod-immutable-kieserver.yaml
- templates/rhdm79-trial-ephemeral.yaml
Signed-off-by: Mikhail Ramendik <mramendi@redhat.com>
> [BXMSDOC-6663] Editorial change - add comma

- templates/rhdm710-authoring-ha.yaml
- templates/rhdm710-authoring.yaml
- templates/rhdm710-kieserver.yaml
- templates/rhdm710-prod-immutable-kieserver-amq.yaml
- templates/rhdm710-prod-immutable-kieserver.yaml
- templates/rhdm710-trial-ephemeral.yaml
See: https://issues.redhat.com/browse/RHPAM-3245
Signed-off-by: Tarun Khandelwal <tarkhand@redhat.com>
> [RHPAM-3245] - Change resource requirements for BC and KIE Server

- controller/artifact-overrides.yaml
- controller/branch-overrides.yaml
- controller/tag-overrides.yaml
- decisioncentral/artifact-overrides.yaml
- decisioncentral/branch-overrides.yaml
- decisioncentral/tag-overrides.yaml
- kieserver/artifact-overrides.yaml
- kieserver/branch-overrides.yaml
- kieserver/tag-overrides.yaml
Signed-off-by: desmax74 <mdessi@redhat.com>
> [RHDM-1432] Update EAP version from 7.3.3 on PAM/DM

- controller/artifact-overrides.yaml
- controller/branch-overrides.yaml
- controller/tag-overrides.yaml
- decisioncentral/artifact-overrides.yaml
- decisioncentral/branch-overrides.yaml
- decisioncentral/tag-overrides.yaml
- kieserver/artifact-overrides.yaml
- kieserver/branch-overrides.yaml
- kieserver/tag-overrides.yaml
Signed-off-by: desmax74 <mdessi@redhat.com>
> [RHDM-1432] Update EAP version from 7.3.3 on PAM/DM 7.9.x

- controller/image.yaml
- decisioncentral/image.yaml
- kieserver/image.yaml
> [KIECLOUD-435] - Remove deprecated -released tags from image.yaml files

- controller/README.adoc
- controller/image.yaml
- controller/tag-overrides.yaml
- decisioncentral/README.adoc
- decisioncentral/image.yaml
- decisioncentral/tag-overrides.yaml
- kieserver/README.adoc
- kieserver/image.yaml
- kieserver/tag-overrides.yaml
- rhdm79-image-streams.yaml
- templates/docs/rhdm79-authoring-ha.adoc
- templates/docs/rhdm79-authoring.adoc
- templates/docs/rhdm79-kieserver.adoc
- templates/docs/rhdm79-prod-immutable-kieserver-amq.adoc
- templates/docs/rhdm79-prod-immutable-kieserver.adoc
- templates/docs/rhdm79-trial-ephemeral.adoc
- templates/rhdm79-authoring-ha.yaml
- templates/rhdm79-authoring.yaml
- templates/rhdm79-kieserver.yaml
- templates/rhdm79-prod-immutable-kieserver-amq.yaml
- templates/rhdm79-prod-immutable-kieserver.yaml
- templates/rhdm79-trial-ephemeral.yaml
See: https://issues.redhat.com/browse/KIECLOUD-467
> [KIECLOUD-467] - Prepare RHDM and RHPAM 7.9.x branches for 7.9.1 release

- quickstarts/hello-rules/README.md
- templates/rhdm710-authoring-ha.yaml
- templates/rhdm710-prod-immutable-kieserver-amq.yaml
> [KIECLOUD-474] - Increase AMQ broker version to 7.8

- controller/branch-overrides.yaml
- controller/image.yaml
- controller/tag-overrides.yaml
- decisioncentral/branch-overrides.yaml
- decisioncentral/image.yaml
- decisioncentral/tag-overrides.yaml
- kieserver/branch-overrides.yaml
- kieserver/image.yaml
- kieserver/tag-overrides.yaml
https://issues.redhat.com/browse/RHPAM-3283
Signed-off-by: Tarun Khandelwal <tarkhand@redhat.com>
> [RHDM-1522] - Align the RHDM image modules with JBoss EAP modules 7.3.x branch

- controller/artifact-overrides.yaml
- controller/branch-overrides.yaml
- controller/tag-overrides.yaml
- decisioncentral/artifact-overrides.yaml
- decisioncentral/branch-overrides.yaml
- decisioncentral/tag-overrides.yaml
- kieserver/artifact-overrides.yaml
- kieserver/branch-overrides.yaml
- kieserver/tag-overrides.yaml
See: https://issues.redhat.com/browse/RHDM-1512
Signed-off-by: desmax74 <mdessi@redhat.com>
> [RHDM-1512] Update EAP version from 7.3.4 on PAM/DM 7.10.x

- controller/branch-overrides.yaml
- decisioncentral/branch-overrides.yaml
- kieserver/branch-overrides.yaml
> [KIECLOUD-487] - update branch overrides to 7.10.x branch

- Makefile
- README.md
See: https://issues.redhat.com/browse/KIECLOUD-490
Signed-off-by: Tarun Khandelwal <tarkhand@redhat.com>
> [KIECLOUD-490] - Provide Make command to build rhdm images

- kieserver/image.yaml
> [RHPAM - 3499] - [ONE-OFF](7.9.1) Make pulling of dependencies and kjar validation skippable in kie-server lauch script

- controller/artifact-overrides.yaml
- controller/branch-overrides.yaml
- controller/tag-overrides.yaml
- decisioncentral/artifact-overrides.yaml
- decisioncentral/branch-overrides.yaml
- decisioncentral/tag-overrides.yaml
- kieserver/artifact-overrides.yaml
- kieserver/branch-overrides.yaml
- kieserver/tag-overrides.yaml
See: https://issues.redhat.com/browse/RHDM-1640
> [RHDM-1640] - Update EAP version from 7.3.6 on PAM/DM 7.11.x

- controller/image.yaml
- decisioncentral/image.yaml
- kieserver/image.yaml
See: https://issues.redhat.com/browse/KIECLOUD-518
> [KIECLOUD-518] - Update RHSSO EAP adatpers from 7.3.1 to 7.4.5

- .circleci/config.yml
- README.md
- controller/README.adoc
- controller/image.yaml
- controller/tag-overrides.yaml
- decisioncentral/README.adoc
- decisioncentral/image.yaml
- decisioncentral/tag-overrides.yaml
- kieserver/README.adoc
- kieserver/image.yaml
- kieserver/tag-overrides.yaml
- quickstarts/hello-rules-multi-module/README.md
- quickstarts/hello-rules-multi-module/pom.xml
- quickstarts/hello-rules/README.md
- quickstarts/hello-rules/pom.xml
- rhdm712-image-streams.yaml
- templates/docs/README.adoc
- templates/docs/rhdm712-authoring-ha.adoc
- templates/docs/rhdm712-authoring.adoc
- templates/docs/rhdm712-kieserver.adoc
- templates/docs/rhdm712-prod-immutable-kieserver-amq.adoc
- templates/docs/rhdm712-prod-immutable-kieserver.adoc
- templates/docs/rhdm712-trial-ephemeral.adoc
- templates/rhdm712-authoring-ha.yaml
- templates/rhdm712-authoring.yaml
- templates/rhdm712-kieserver.yaml
- templates/rhdm712-prod-immutable-kieserver-amq.yaml
- templates/rhdm712-prod-immutable-kieserver.yaml
- templates/rhdm712-trial-ephemeral.yaml
See: https://issues.redhat.com/browse/KIECLOUD-535
> Prepare master branch of all image repositories for 7.12 release

- controller/branch-overrides.yaml
- decisioncentral/branch-overrides.yaml
- kieserver/branch-overrides.yaml
> Update branch-overrides.yaml to match 7.11.x branch.

- README.md
- templates/docs/README.adoc
> adocs update

- .circleci/config.yml
- controller/image.yaml
- decisioncentral/image.yaml
- kieserver/image.yaml
Signed-off-by: desmax74 <mdessi@redhat.com>
> [KIECLOUD-532] JDBC driver on RHDM/RHPAM images

- README.md
- controller/image.yaml
- controller/tag-overrides.yaml
- decisioncentral/image.yaml
- decisioncentral/tag-overrides.yaml
- kieserver/image.yaml
- kieserver/tag-overrides.yaml
- rhdm711-image-streams.yaml
- templates/docs/rhdm711-authoring-ha.adoc
- templates/docs/rhdm711-authoring.adoc
- templates/docs/rhdm711-kieserver.adoc
- templates/docs/rhdm711-prod-immutable-kieserver-amq.adoc
- templates/docs/rhdm711-prod-immutable-kieserver.adoc
- templates/docs/rhdm711-trial-ephemeral.adoc
- templates/rhdm711-authoring-ha.yaml
- templates/rhdm711-authoring.yaml
- templates/rhdm711-kieserver.yaml
- templates/rhdm711-prod-immutable-kieserver-amq.yaml
- templates/rhdm711-prod-immutable-kieserver.yaml
- templates/rhdm711-trial-ephemeral.yaml
See: https://issues.redhat.com/browse/KIECLOUD-551
> [KIECLOUD-551] - Prepare RHPAM and RHDM for 7.11.1 release

- controller/tag-overrides.yaml
- decisioncentral/branch-overrides.yaml
- decisioncentral/tag-overrides.yaml
- kieserver/branch-overrides.yaml
- kieserver/tag-overrides.yaml
Adjust permissions on openshift-layer module on cct_module
> [KIECLOUD-553] - update cct_module tag to 0.39.4

- templates/rhdm712-authoring-ha.yaml
[KIECLOUD-564] 7.12 Checkpoint - Increase JDG version to 8.x
https://issues.redhat.com/browse/KIECLOUD-564
Signed-off-by: Achyut Madhusudan <amadhusu@redhat.com>
> [KIECLOUD-564]-Increased JDG version to 8.x

- controller/artifact-overrides.yaml
- controller/branch-overrides.yaml
- controller/image.yaml
- controller/tag-overrides.yaml
- decisioncentral/artifact-overrides.yaml
- decisioncentral/branch-overrides.yaml
- decisioncentral/image.yaml
- decisioncentral/tag-overrides.yaml
- kieserver/artifact-overrides.yaml
- kieserver/branch-overrides.yaml
- kieserver/image.yaml
- kieserver/tag-overrides.yaml
See: https://issues.redhat.com/browse/KIECLOUD-562
> [KIECLOUD-562] - Upgrade EAP to 7.4.0 on RHDM and RHPAM images

- controller/branch-overrides.yaml
- controller/tag-overrides.yaml
- decisioncentral/branch-overrides.yaml
- decisioncentral/tag-overrides.yaml
- kieserver/branch-overrides.yaml
- kieserver/tag-overrides.yaml
See: https://issues.redhat.com/browse/KIECLOUD-583
> [KIECLOUD-583] - Upgrade EAP to 7.4.1 on RHDM and RHPAM images

- controller/image.yaml
- decisioncentral/image.yaml
- kieserver/image.yaml
See: https://issues.redhat.com/browse/KIECLOUD-565
> [KIECLOUD-565] - Update RHSSO EAP adatpers from 7.4.5 to 7.5.0

- controller/image.yaml
- decisioncentral/image.yaml
- kieserver/image.yaml
See: https://issues.redhat.com/browse/KIECLOUD-544
> [KIECLOUD-544] - Combine the prometheus agent and config modules

- controller/image.yaml
- decisioncentral/image.yaml
- kieserver/image.yaml
- templates/rhdm712-authoring-ha.yaml
- templates/rhdm712-authoring.yaml
- templates/rhdm712-kieserver.yaml
- templates/rhdm712-prod-immutable-kieserver-amq.yaml
- templates/rhdm712-prod-immutable-kieserver.yaml
- templates/rhdm712-trial-ephemeral.yaml
perspective
Cherry-picks: https://github.com/jboss-container-images/rhdm-7-openshift-image/pull/457
> [RHPAM-4026] - [OpenShift] Users and Groups are not displayed in Admin perspective

- templates/rhdm713-authoring-ha.yaml
- templates/rhdm713-authoring.yaml
- templates/rhdm713-kieserver.yaml
- templates/rhdm713-prod-immutable-kieserver-amq.yaml
- templates/rhdm713-prod-immutable-kieserver.yaml
- templates/rhdm713-trial-ephemeral.yaml
> docs review - capitalize all ldap occurrencies

- templates/rhdm713-authoring-ha.yaml
- templates/rhdm713-authoring.yaml
- templates/rhdm713-kieserver.yaml
- templates/rhdm713-prod-immutable-kieserver-amq.yaml
- templates/rhdm713-prod-immutable-kieserver.yaml
- templates/rhdm713-trial-ephemeral.yaml
Cherry-picks https://github.com/jboss-container-images/rhdm-7-openshift-image/pull/465
> fix small typo on ldap keep non mapped roles

- templates/docs/rhdm712-authoring-ha.adoc
- templates/docs/rhdm712-authoring.adoc
- templates/docs/rhdm712-kieserver.adoc
- templates/docs/rhdm712-prod-immutable-kieserver-amq.adoc
- templates/docs/rhdm712-prod-immutable-kieserver.adoc
- templates/docs/rhdm712-trial-ephemeral.adoc
See: https://issues.redhat.com/browse/KIECLOUD-614
> update adocs due KIECLOUD-614

- templates/docs/rhdm712-authoring-ha.adoc
> update templates' adoc
