decisioncentral/image.yaml, kieserver/image.yaml
Depends on
https://github.com/jboss-openshift/cct_module/pull/175
https://github.com/jboss-container-images/jboss-kie-modules/pull/1
=> [CLOUD-2235] KIE specific concreate modules moved to own repo

templates/rhdm70-kieserver-basic-s2i.yaml, templates/rhdm70-kieserver-https-s2i.yaml
=> [RHDM-375] - Remove controller environment variables from S2I templates

decisioncentral/image.yaml, kieserver/image.yaml
https://issues.jboss.org/browse/CLOUD-2235
The KIE modules will be moving from cct_modules to
the new repository added in this commit.
=> [CLOUD-2235] Add jboss-kie-modules module repository

templates/rhdm70-kieserver.yaml
[RHDM-508] rhdm70-kieserver OpenShift template broken. Unable to import.
https://issues.jboss.org/browse/RHDM-508
=> [RHDM-508] rhdm70-kieserver OpenShift template broken. Unable to import.

templates/rhdm70-full.yaml
[RHDM-536] Decision Central OpenShift container does not expose Git HTTP and SSH ports
https://issues.jboss.org/browse/RHDM-536
=> [RHDM-536] Decision Central OpenShift container does not expose Git HTTP and SSH ports

templates/rhdm70-full.yaml
- add msising maven env on decision central
=> [RHDM-319] - OpenShift - default Maven user should not be admin (#47)

templates/rhdm70-kieserver-basic-s2i.yaml, templates/rhdm70-kieserver-https-s2i.yaml
To fix an error :
oc create -f rhdm70-kieserver-https-s2i.yaml 
Error from server (BadRequest): error when creating "rhdm70-kieserver-https-s2i.yaml": Template in version "v1" cannot be handled as a Template: [pos 14188]: json: expect char '"' but got char 't'
=> [RHDM-592] - Fix invalid value in template yaml

decisioncentral/image.yaml, kieserver/image.yaml
[RHDM-608] rhdm70-dev branch should use CE sprint-18
https://issues.jboss.org/browse/RHDM-608
=> [RHDM-608] rhdm70-dev branch should use CE sprint-18

README.md, decisioncentral/image.yaml, kieserver/image.yaml, rhdm70-image-streams.yaml, templates/rhdm70-full.yaml, templates/rhdm70-kieserver-basic-s2i.yaml, templates/rhdm70-kieserver-https-s2i.yaml, templates/rhdm70-kieserver.yaml
[RHDM-630] Update RHDM OpenShift images from 7.0.1.CR1 to 7.0.1.CR2
https://issues.jboss.org/browse/RHDM-630
=> [RHDM-630] Update RHDM OpenShift images from 7.0.1.CR1 to 7.0.1.CR2

kieserver/image.yaml
Fix https://issues.jboss.org/browse/RHDM-381
=> [RHDM-381] Fix typo in OpenShift tags in kieserver image

kieserver/image.yaml, templates/rhdm70-full.yaml, templates/rhdm70-kieserver-basic-s2i.yaml, templates/rhdm70-kieserver-https-s2i.yaml, templates/rhdm70-kieserver.yaml
- [RHDM-381] Fix typo in OpenShift tags in kieserver image
- [RHDM-319] - OpenShift - default Maven user should not be admin
- [RHDM-587] - Allow KIE server / OpenShift to be completely immutable
- [RHDM-536] Allow access to the decision-central image git repository
=> 7.0.1 cherry picks

templates/rhdm70-full.yaml, templates/rhdm70-kieserver-basic-s2i.yaml, templates/rhdm70-kieserver-https-s2i.yaml, templates/rhdm70-kieserver.yaml
[RHDM-672] Remove EAP ADMIN parameters from templates in RHDM
https://issues.jboss.org/browse/RHDM-672
=> [RHDM-672] Remove EAP ADMIN parameters from templates in RHDM

templates/rhdm70-kieserver-basic-s2i.yaml, templates/rhdm70-kieserver-https-s2i.yaml, templates/rhdm70-kieserver.yaml
[RHDM-673] Missing MAVEN_REPO_SERVICE parameter in kieserver templates in RHDM
https://issues.jboss.org/browse/RHDM-673
=> [RHDM-673] Missing MAVEN_REPO_SERVICE parameter in kieserver templates in RHDM

templates/rhdm71-full.yaml, templates/rhdm71-kieserver-basic-s2i.yaml, templates/rhdm71-kieserver-https-s2i.yaml, templates/rhdm71-kieserver.yaml
[RHDM-708] Replace scripts in probes for Kie Server Image with REST calls
https://issues.jboss.org/browse/RHDM-708
=> [RHDM-708] Replace scripts in probes for Kie Server Image with REST calls

templates/rhdm71-full.yaml
[RHDM-722] GIT_HOOKS_DIR parameter not exposed in RHDM templates
https://issues.jboss.org/browse/RHDM-722
=> [RHDM-722] GIT_HOOKS_DIR parameter not exposed in RHDM templates

templates/rhdm71-authoring-ha.yaml, templates/rhdm71-authoring.yaml, templates/rhdm71-kieserver.yaml, templates/rhdm71-prod-immutable-kieserver.yaml, templates/rhdm71-trial-ephemeral.yaml
[RHDM-735] RHDM maven repository id should be configurable instead of generated
https://issues.jboss.org/browse/RHDM-735
=> [RHDM-735] RHDM maven repository id should be configurable instead of generated

templates/rhdm71-trial-ephemeral.yaml
[RHDM-689] change KIE_ADMIN_PWD and KIE_SERVER_PWD to DEFAULT_PASSWORD
https://issues.jboss.org/browse/RHDM-689
=> [RHDM-689] change KIE_ADMIN_PWD and KIE_SERVER_PWD to DEFAULT_PASSWORD

templates/rhdm71-authoring-ha.yaml, templates/rhdm71-authoring.yaml, templates/rhdm71-kieserver.yaml, templates/rhdm71-prod-immutable-kieserver.yaml, templates/rhdm71-trial-ephemeral.yaml
[RHDM-670] set controller protocol properly for kieserver
https://issues.jboss.org/browse/RHDM-670
=> [RHDM-670] set controller protocol properly for kieserver

templates/optaweb/rhdm72-optaweb-employee-rostering-postgresql.yaml
[RHPAM-1717] Update default vaule of PostgreSQL ImageStream Tag in OpenShift templates
https://issues.jboss.org/browse/RHPAM-1717
=> [RHPAM-1717] Update default vaule of PostgreSQL ImageStream Tag in OpenShift templates

controller/dev-overrides.yaml, decisioncentral/dev-overrides.yaml, kieserver/dev-overrides.yaml, optaweb-employee-rostering/dev-overrides.yaml
[KIECLOUD-20] updated jboss-eap-modules from EAP72-CR5 branch to EAP72-CR5-1 tag
=> [KIECLOUD-20] updated jboss-eap-modules from EAP72-CR5 branch to EAP72-CR5-1 tag

controller/dev-overrides.yaml, controller/rel-overrides.yaml, decisioncentral/dev-overrides.yaml, decisioncentral/rel-overrides.yaml, kieserver/dev-overrides.yaml, kieserver/rel-overrides.yaml, optaweb-employee-rostering/dev-overrides.yaml, optaweb-employee-rostering/rel-overrides.yaml
[KIECLOUD-20] final move to EAP_720 tags, which are identical to EAP72_CR5 tag in jboss-eap-7-image and EAP72_CR5-1 tag in jboss-eap-modules
=> [KIECLOUD-20] final move to EAP_720 tags

controller/image.yaml, decisioncentral/image.yaml, kieserver/image.yaml, optaweb-employee-rostering/image.yaml, templates/rhdm73-trial-ephemeral.yaml
[KIECLOUD-107] Add Prometheus module to EAP-based RHDM 7 images
https://issues.jboss.org/browse/KIECLOUD-107
=> [KIECLOUD-107] Add Prometheus config to EAP-based RHDM 7 images

templates/rhdm73-authoring-ha.yaml
JIRA Link: https://issues.jboss.org/browse/KIECLOUD-114
After some discussion, instead of adding app labels in all templates, we decided to remove the app labels as they are automatically generated by OpenShift. Although I still believe we must change the application
label to another thing as app and application labels semantically mean the same.
Signed-off-by: rimolive <ricardo.martinelli.oliveira@gmail.com>
=> [KIECLOUD-114] Remove app label from authoring HA template

templates/rhdm73-authoring-ha.yaml
JIRA Link: https://issues.jboss.org/browse/RHDM-870
"ping" must be used as Service name as AMQ clustering configuration hard-coded this name.
Signed-off-by: rimolive <ricardo.martinelli.oliveira@gmail.com>
=> [RHDM-870] Fix AMQ ping service name

templates/rhdm73-authoring-ha.yaml
[KIECLOUD-148] System property org.uberfire.nio.git.ssh.hostname not provided
https://issues.jboss.org/browse/KIECLOUD-148
=> [KIECLOUD-148] (7.3.x) System property org.uberfire.nio.git.ssh.hostname not provided

templates/rhdm73-trial-ephemeral.yaml
[KIECLOUD-159] Remove prometheus template params from trial-ephemeral templates in 7.3.0
https://issues.jboss.org/browse/KIECLOUD-159 
=> [KIECLOUD-159] Remove prometheus template params from trial-ephemeral templates in 7.3.0

templates/rhdm74-authoring-ha-datagrid.yaml, templates/rhdm74-authoring-ha.yaml, templates/rhdm74-authoring.yaml, templates/rhdm74-kieserver.yaml, templates/rhdm74-prod-immutable-kieserver.yaml, templates/rhdm74-trial-ephemeral.yaml
[RHDM-883] Setting Maven Mirror URL does not exclude Decision Central
https://issues.jboss.org/browse/RHDM-883
=> [RHDM-883] Setting Maven Mirror URL does not exclude Decision Central

controller/branch-overrides.yaml, decisioncentral/branch-overrides.yaml, kieserver/branch-overrides.yaml, optaweb-employee-rostering/branch-overrides.yaml
[RHDM-894] Update RHDM images to use RHEL8 (UBI) base layer
https://issues.jboss.org/browse/RHDM-894
=> [RHDM-894] Update RHDM images to use RHEL8 (UBI) base layer

templates/rhdm75-authoring-ha.yaml
[RHPAM-2354] OutOfMemoryError on Datagrid cause issues on project import indexing
https://issues.jboss.org/browse/RHPAM-2354
=> [RHPAM-2354] OutOfMemoryError on Datagrid cause issues on project import indexing

kieserver/image.yaml
[RHDM-1096] - Add missing environment variable for optaplanner thread pool queue size
See: https://issues.jboss.org/browse/RHDM-1096
Signed-off-by: Mauricio Magnani <mmagnani@redhat.com>
=> [RHDM-1096] - Add missing environment variable for optaplanner thread pool queue size

templates/rhdm76-authoring-ha.yaml, templates/rhdm76-authoring.yaml, templates/rhdm76-kieserver.yaml, templates/rhdm76-prod-immutable-kieserver-amq.yaml, templates/rhdm76-prod-immutable-kieserver.yaml, templates/rhdm76-trial-ephemeral.yaml
https://issues.jboss.org/browse/KIECLOUD-346
=> [KIECLOUD-346] Editorial changes: username to user name and typos

templates/rhdm77-authoring-ha.yaml
[RHDM-1191] Increase DataGrid 7.3 image tag version to 1.4 in OpenShift templates
https://issues.redhat.com/browse/RHDM-1191
=> [RHDM-1191] Increase DataGrid 7.3 image tag version to 1.4 in OpenShift templates

templates/rhdm77-authoring-ha.yaml, templates/rhdm77-authoring.yaml
[RHPAM-2732] Kie Server is not connected to BC in Authoring template
https://issues.redhat.com/browse/RHPAM-2732
=> [RHPAM-2732] Kie Server is not connected to BC in Authoring template
